### ISSUE TITLE
Due Date

### ISSUE THREAD

**Issue by dnxjay** [ubsuny/CP1-24-final#1]
Does anyone know what date and time is the final project due on?

**Comment by jkblc** [comment]
@laserlab

**Comment by dnxjay** [comment]
any update on this @laserlab

**Comment by p-pxmpo** [comment]
@laserlab same question

**Comment by dnxjay** [comment]
Does anyone have the answer to this yet? @jkblc @p-pxmpo

**Comment by kylemasc917** [comment]
Its due Wednesday Dec. 11th

**Comment by p-pxmpo** [comment]
> Does anyone have the answer to this yet? @jkblc @p-pxmpo

still working on it
